In [4]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.2.2
1.26.4

In [ ]:
# Major Data Structure
# 1. Series - One Dimentional Array
# 2. DataFrame - Two Dimentional Array
# 3. Panel - Three Dimentional Array

a = pd.Series([1,2,3,4,5])
print(a)
b = pd.Series([1,2,3,4,5], index=['e','f','g','h','i'])
print(b)

0    1
1    2
2    3
3    4
4    5
dtype: int64
e    1
f    2
g    3
h    4
i    5
dtype: int64

In [12]:
# Describe

print(a.describe())
print(a.min())

count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64
1

In [ ]:
# Data Manuplation
doubled = a.map(lambda x: x*2)
print(doubled)
b = pd.Series([5,2,3,8,4,2,7,9,8,9])
a = b.sort_values()
print(a)

0    1047655978
dtype: int64
1    2
5    2
2    3
4    4
0    5
6    7
3    8
8    8
7    9
9    9
dtype: int64

In [6]:
# inplace & Dropped
s1 = pd.array([1,2,3,4,5])
print(s1)
dropped_series = s1.delete(0);
print(dropped_series)

<IntegerArray>
[1, 2, 3, 4, 5]
Length: 5, dtype: Int64
<IntegerArray>
[2, 3, 4, 5]
Length: 4, dtype: Int64

In [3]:
# Handling Missing Data
s4 = pd.Series([1, 2, 3, 4, 5, 6, np.nan])

print(s4)
print(s4.isnull())
print(s4.notnull())  # This will work perfectly now!
print(s4.fillna(0))
print(s4.dropna())

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    NaN
dtype: float64
0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool
0     True
1     True
2     True
3     True
4     True
5     True
6    False
dtype: bool
0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    0.0
dtype: float64
0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
dtype: float64

In [73]:
# Indexing and slicing
s6 = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
print(s6)
print(s6.iloc[4])
print(s6.iloc[1:3])
print(s6.loc['e'])
print(s6.loc['b':'d'])

a    1
b    2
c    3
d    4
e    5
dtype: int64
5
b    2
c    3
dtype: int64
5
b    2
c    3
d    4
dtype: int64

In [ ]:
# Filter And Aggirigation
s7 = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
print(s7[s7 > 2])
print(s7.sum())
print(s7.cumsum())
print(s7.aggregate(['sum','mean','std'])) # One Or More Operation

c    3
d    4
e    5
dtype: int64
15
a     1
b     3
c     6
d    10
e    15
dtype: int64
sum     15.000000
mean     3.000000
std      1.581139
dtype: float64

In [6]:
# Creating 20 records of employee data
emp_data = {
    'Emp_ID': range(101, 121),
    'Name': [
        'Alice', 'Bob', 'Charlie', 'David', 'Eva', 
        'Frank', 'Grace', 'Henry', 'Ivy', 'Jack', 
        'Karl', 'Liam', 'Mia', 'Noah', 'Olivia', 
        'Paul', 'Quinn', 'Rachel', 'Sam', 'Tom'
    ],
    'Department': [
        'HR', 'IT', 'Finance', 'IT', 'Marketing', 
        'Sales', 'HR', 'Finance', 'IT', 'Sales', 
        'Marketing', 'IT', 'Finance', 'HR', 'Sales', 
        'IT', 'Finance', 'Marketing', 'Sales', 'HR'
    ],
    'Salary': [
        65000, 85000, np.nan, 90000, 72000, 
        58000, 67000, 95000, np.nan, 62000, 
        71000, 105000, 88000, 69000, 60000, 
        np.nan, 92000, 74000, 61000, 66000
    ],
    'Hire_Date': [
        '2020-01-15', '2019-05-12', '2021-03-23', '2020-11-01', '2022-02-14',
        '2018-08-19', '2021-06-01', '2017-04-11', '2023-01-10', '2019-10-05',
        '2022-07-19', '2015-03-30', '2020-09-15', None, '2021-11-20',
        '2018-12-05', '2016-07-22', '2023-05-01', '2020-04-18', '2022-10-01'
    ],
    'Performance_Rating': [
        'Excellent', 'Good', 'Good', 'Excellent', None,
        'Average', 'Excellent', 'Good', 'Average', 'Good',
        'Excellent', 'Excellent', 'Average', 'Good', 'Average',
        'Good', 'Excellent', None, 'Excellent', 'Average'
    ]
}

contacts_data = {
    'Name': [
        'Alice', 'Bob', 'Charlie', 'David', 'Eva', 
        'Frank', 'Grace', 'Henry', 'Ivy', 'Jack', 
        'Karl', 'Liam', 'Mia', 'Noah', 'Olivia', 
        'Paul', 'Quinn', 'Rachel', 'Sam', 'Tom'
    ],
    'Email': [
        'alice@company.com', 'bob@company.com', 'charlie@company.com', 'david@company.com', 'eva@company.com',
        'frank@company.com', 'grace@company.com', 'henry@company.com', 'ivy@company.com', 'jack@company.com',
        'karl@company.com', 'liam@company.com', 'mia@company.com', 'noah@company.com', 'olivia@company.com',
        'paul@company.com', 'quinn@company.com', 'rachel@company.com', 'sam@company.com', 'tom@company.com'
    ],
    'Phone': [
        '555-0101', '555-0102', '555-0103', '555-0104', '555-0105',
        '555-0106', '555-0107', '555-0108', '555-0109', '555-0110',
        '555-0111', '555-0112', '555-0113', '555-0114', '555-0115',
        '555-0116', '555-0117', '555-0118', '555-0119', '555-0120'
    ],
    'City': [
        'New York', 'Chicago', 'Boston', 'Austin', 'Chicago',
        'Miami', 'New York', 'Boston', 'Austin', 'San Francisco',
        'Miami', 'San Francisco', 'New York', 'Austin', 'Boston',
        'Chicago', 'Miami', 'San Francisco', 'Austin', 'New York'
    ]
}

# Load into DataFrame
df_emp = pd.DataFrame(emp_data)
df_contacts = pd.DataFrame(contacts_data)

# Display the DataFrame
print(df_emp.head(2))
print(df_contacts.head(2))

merged_df = pd.merge(df_emp,df_contacts, on='Name')
print(merged_df.head(2))
merged_df.head(2)

   Emp_ID   Name Department   Salary   Hire_Date Performance_Rating
0     101  Alice         HR  65000.0  2020-01-15          Excellent
1     102    Bob         IT  85000.0  2019-05-12               Good
    Name              Email     Phone      City
0  Alice  alice@company.com  555-0101  New York
1    Bob    bob@company.com  555-0102   Chicago
   Emp_ID   Name Department   Salary   Hire_Date Performance_Rating  \
0     101  Alice         HR  65000.0  2020-01-15          Excellent
1     102    Bob         IT  85000.0  2019-05-12               Good

               Email     Phone      City
0  alice@company.com  555-0101  New York
1    bob@company.com  555-0102   Chicago

,Emp_ID,Name,Department,Salary,Hire_Date,Performance_Rating,Email,Phone,City
0,101,Alice,HR,65000.0,2020-01-15,Excellent,alice@company.com,555-0101,New York
1,102,Bob,IT,85000.0,2019-05-12,Good,bob@company.com,555-0102,Chicago

In [7]:
# Import a dataset
df = pd.read_csv('filmtv_movies.csv')
df.head(1)
df.tail(1)
df.shape
df.columns
df.dtypes
#df.describe()
titles = df.loc[10:12,['title','year','genre']]
print(titles)
titles = df.iloc[10:12,[1,2,3]]
titles

                        title  year        genre
10  A Ghentar si muore facile  1968    Adventure
11    Sleeping with the Enemy  1990        Drama
12        In Bed With Madonna  1990  Documentary

                        title  year      genre
10  A Ghentar si muore facile  1968  Adventure
11    Sleeping with the Enemy  1990      Drama

In [8]:
# Filtering Data set
dramas = df.loc[df['genre'] == 'Drama']
dramas

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
6,22,A ciascuno il suo,1967,Drama,93,Italy,Elio Petri,"Gian Maria Volonté, Irene Papas, Gabriele Ferz...",7.6,7.68,7.0,139,Investigations into two murders committed in a...,"Champion of the cinema of civil commitment, El...",0,2,3,3,1
9,26,At Close Range,1986,Drama,115,United States,James Foley,"Christopher Walken, Sean Penn, Chris Penn, Mar...",7.5,7.64,7.0,90,Young Brad (Penn) lives with his grandmother a...,"Powerful and brutal thriller, second work by J...",1,3,2,4,2
11,32,Sleeping with the Enemy,1990,Drama,96,United States,Joseph Ruben,"Julia Roberts, Patrick Bergin, Kevin Anderson,...",5.0,4.33,6.0,111,Martin and Laura Burney have been married for ...,"Some twist is actually well placed, but from a...",1,3,2,3,1
18,49,Fail-Safe,1964,Drama,110,United States,Sidney Lumet,"Henry Fonda, Dan O'Herlihy, Walter Matthau, Do...",8.2,8.20,8.0,73,When the US strategic air command is alerted t...,"With this film Lumet returns great, after a pe...",0,3,3,3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41368,229838,Tereddüt Çizgisi,2023,Drama,84,"Turkey, France, Romania, Spain",Selman Nacar,"Tülin Özen, Görkem Ipek",7.0,7.00,7.0,3,All over a day. A criminal lawyer is awaiting ...,NaN,0,0,0,0,0
41370,229865,Stolen,2023,Drama,92,India,Karan Tejpal,"Abhishek Banerjee, Harish Khanna, Mia Maelzer,...",5.3,6.00,5.0,4,"The five -month daughter of Jhumpa Mahato, poo...",NaN,0,0,0,0,0
41371,229881,Árni,2023,Drama,103,Hungary,Dorka Vermes,"Péter Turi, Andrea Spolarics",5.3,6.00,5.0,3,A lone nomad who works for an itinerant circus...,NaN,0,0,0,0,0
41372,229883,Kanata no uta,2023,Drama,84,Japan,Kyoshi Sugita,"An Ogawa, Yûko Nakamura, Hidekazu Mashima",5.5,5.00,6.0,3,"The twenty -five year old Haru, committed in a...",NaN,0,0,0,0,0
41390,232203,Mes petites amoureuses,1974,Drama,123,France,Jean Eustache,"Martin Loeb, Jacqueline Dufranne, Jacques Roma...",8.3,8.50,8.0,3,Daniel is a silent boy who observes girls with...,NaN,0,0,0,0,0

In [84]:
# Filtering Data set, Multiple Condition
dramas = df.loc[(df['genre'] == 'Drama') & (df['avg_vote'] >= 10.0 )]
dramas

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
28931,58519,Sex & Mrs. X,2000,Drama,100,United States,Arthur Allan Seidelman,"Jacqueline Bisset, Linda Hamilton, Paolo Segan...",10.0,NaN,10.0,3,Joanna has a life full of certainty and stabil...,NaN,0,0,0,0,0

In [87]:
# iloc
single_row = df.iloc[0]
single_row

filmtv_id                                                       2
title                 Bugs Bunny's Third Movie: 1001 Rabbit Tales
year                                                         1982
genre                                                   Animation
duration                                                       76
country                                             United States
directors                    David Detiege, Art Davis, Bill Perez
actors                                                        NaN
avg_vote                                                      7.7
critics_vote                                                  8.0
public_vote                                                   7.0
total_votes                                                    22
description     With two protruding front teeth, a slightly sl...
notes           These are many small independent stories, whic...
humor                                                           3
rhythm                                                          3
effort                                                          0
tension                                                         0
erotism                                                         0
Name: 0, dtype: object

In [91]:
# iloc
single_data = df.iloc[0,[0,5,6]]
single_data

filmtv_id                                       2
country                             United States
directors    David Detiege, Art Davis, Bill Perez
Name: 0, dtype: object

In [100]:
# iloc
multi_slice = df.iloc[0:10:2,[0,5,6]]
multi_slice

   filmtv_id        country                             directors
0          2  United States  David Detiege, Art Davis, Bill Perez
2         17  United States                           Don Chaffey
4         20          Italy                        Esodo Pratelli
6         22          Italy                            Elio Petri
8         24          Italy          Ray Morrison (Angelo Dorigo)

In [103]:
# Access specifig single value
title_of_match = df.at[0,'country']
title_of_match

'United States'

In [104]:
# Filter movies released after 2010
recent_movies = df[df['year'] > 2010]
recent_movies

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
22817,39955,The Tree of Life,2011,Drama,138,United States,Terrence Malick,"Brad Pitt, Sean Penn, Jessica Chastain, Tye Sh...",7.4,7.43,7.0,476,"Jack, an eleven-year-old boy, lives in the Mid...","Beauty passes through cinema: the director, as...",0,2,4,2,0
23725,41448,Season of the Witch,2011,Adventure,95,United States,Dominic Sena,"Nicolas Cage, Claire Foy, Ron Perlman, Stephen...",4.3,4.13,4.0,153,"During the fourteenth century, when the black ...",Thrown to the wind the attempts to build a bar...,1,2,1,3,0
24186,42398,Restless,2011,Drama,95,United States,Gus Van Sant,"Mia Wasikowska, Schuyler Fisk, Jane Adams, Lus...",6.9,6.59,7.0,151,Enoch is a 17-year-old who lost both parents a...,The director of Last Days returns to spy on th...,2,2,3,1,0
24426,42847,Qualunquemente,2011,Grotesque,96,Italy,Giulio Manfredonia,"Antonio Albanese, Sergio Rubini, Lorenza Indov...",5.6,5.65,6.0,291,Cetto La Qualunque (Albanese) returns to Italy...,The grotesque and at times effective mask rema...,4,3,3,1,1
24427,42848,Una sconfinata giovinezza,2011,Drama,98,Italy,Pupi Avati,"Fabrizio Bentivoglio, Francesca Neri, Serena G...",6.7,6.60,7.0,95,Lino Settembre and his wife Chicca lead a peac...,"Written with the taste of a novelist's plot, i...",2,2,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,4.0,3,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,3,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,6.0,6,A team building conference organized for a gro...,NaN,0,0,0,0,0
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,6.0,5,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,6.0,3,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0

In [106]:
# Highly Rated Thriller
highly_rated_thriller = df[(df['public_vote'] >= 8) & (df['genre'] == 'Thriller' ) ]
highly_rated_thriller

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
21,54,Johnny O'Clock,1947,Thriller,95,United States,Robert Rossen,"Dick Powell, Evelyn Keyes, Lee J. Cobb, Ellen ...",7.8,8.00,8.0,20,Johnny O'Clock (Powell) is a minority partner ...,Columbia took advantage of Dick Powell's recen...,1,3,1,3,1
27,67,You'll Like My Mother,1973,Thriller,94,United States,Lamont Johnson,"Patty Duke, Rosemary Murphy, Richard Thomas, S...",7.8,8.00,8.0,6,"After her husband's death, Francesca decides t...",Specialist Lamont Johnson has built an effecti...,0,3,1,3,0
140,236,Time Without Pity,1956,Thriller,88,Great Britain,Joseph Losey,"Michael Redgrave, Ann Todd, Peter Cushing, Joa...",7.9,8.00,8.0,16,Alec Graham was sentenced to death for killing...,Emigrated to Great Britain after being blackli...,0,3,2,3,0
183,296,Strangers on a Train,1951,Thriller,96,United States,Alfred Hitchcock,"Farley Granger, Robert Walker, Ruth Roman, Leo...",8.4,8.66,8.0,258,Guy Haines is a successful tennis player with ...,"Patricia Highsmith's first novel, that of the ...",1,2,2,4,0
302,478,Gaslight,1944,Thriller,109,United States,George Cukor,"Ingrid Bergman, Charles Boyer, Joseph Cotten, ...",7.8,7.86,8.0,94,"Paula married Gregory, who long ago strangled ...","Nice ""gothic"" melodrama by George Cukor. The m...",2,4,3,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40950,216918,Aru otoko,2022,Thriller,121,Japan,Kei Ishikawa,"Satoshi Tsumabuki, Sakura Andô, Masataka Kubot...",7.3,7.00,8.0,3,Akira works as a lawyer and one day he meets a...,NaN,0,0,0,0,0
41118,220183,The Other Child,2022,Thriller,114,South Korea,Jin-young Kim,"Kim Min-Jae, Hyo-ju Park",5.3,3.00,8.0,3,The members of a family deeply likes the disap...,NaN,0,0,0,0,0
41200,221403,Anatomie d'une chute,2023,Thriller,151,France,Justine Triet,"Sandra Hüller, Samuel Theis, Swann Arlaud, Jeh...",7.3,7.00,8.0,4,"Samuel is found dead, buried in the snow outsi...",NaN,0,0,0,0,0
41218,221890,Ming On,2022,Thriller,109,Hong Kong,Soi Cheang,"Ka-Tung Lam, Charm Man Chan, Wing-Sze Ng, Lok ...",7.8,8.00,8.0,4,"A master of fortune teller (Gordon Lam), very ...",NaN,0,0,0,0,0
41246,223251,Twisted Nerve,1968,Thriller,112,Great Britain,Roy Boulting,"Hayley Mills, Hywel Bennett, Billie Whitelaw, ...",7.5,7.00,8.0,3,Martin Durnley (Hywel Bennett) is a twenty yea...,NaN,0,0,0,0,0

In [ ]:
df.drop(labels='title',axis=1)
# if we use inplace, drop the label completly df.drop(labels='title',axis=1,inplace=True)

,filmtv_id,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,1982,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,4.0,3,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0
41395,232893,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,3,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0
41396,232915,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,6.0,6,A team building conference organized for a gro...,NaN,0,0,0,0,0
41397,232919,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,6.0,5,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0
41398,232920,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,6.0,3,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0

In [113]:
df.head(1)
df.at[0,'year'] = 2007
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,2007,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,4.0,3,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,3,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,6.0,6,A team building conference organized for a gro...,NaN,0,0,0,0,0
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,6.0,5,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,6.0,3,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0

In [114]:
df['reviewer'] = 'default Value'
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,public_vote,total_votes,description,notes,humor,rhythm,effort,tension,erotism,reviewer
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,2007,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,7.0,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0,default Value
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,7.0,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0,default Value
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,5.0,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0,default Value
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,6.0,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2,default Value
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,7.0,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0,default Value
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,4.0,3,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0,default Value
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,3.0,3,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0,default Value
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,6.0,6,A team building conference organized for a gro...,NaN,0,0,0,0,0,default Value
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,6.0,5,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0,default Value
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,6.0,3,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0,default Value

In [115]:
# Add New column based on the condition
df.loc[df['year']< 2000,'classic'] = True
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,...,total_votes,description,notes,humor,rhythm,effort,tension,erotism,reviewer,classic
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,2007,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,...,22,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0,default Value,NaN
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,...,4,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0,default Value,True
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,...,10,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0,default Value,True
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,...,18,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2,default Value,True
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,...,15,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0,default Value,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,...,3,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0,default Value,NaN
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,...,3,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0,default Value,NaN
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,...,6,A team building conference organized for a gro...,NaN,0,0,0,0,0,default Value,NaN
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,...,5,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0,default Value,NaN
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,...,3,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0,default Value,NaN

In [116]:
# Add New column based on the condition
df.loc[df['year']< 2000,['classic','must_watch']] = [True,True]
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,...,description,notes,humor,rhythm,effort,tension,erotism,reviewer,classic,must_watch
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,2007,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,...,"With two protruding front teeth, a slightly sl...","These are many small independent stories, whic...",3,3,0,0,0,default Value,NaN,NaN
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,...,"Samantha, not yet eighteen, leaves the comfort...","Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0,default Value,True,True
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,...,"In the Australia of the pioneers, a boy and a ...","""Ecological"" story with a happy ending, not wi...",1,2,1,0,0,default Value,True,True
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,...,Five boys from Baltimore have a habit of meeti...,A cast of will be famous for Levinson's direct...,2,2,0,1,2,default Value,True,True
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,...,"With a stratagem, the penniless and somewhat p...",Taken from the play by Armando Curcio that the...,3,1,1,0,0,default Value,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,...,Celeste is an attractive waitress in the forti...,Freely taken from a true story.,0,0,0,0,0,default Value,NaN,NaN
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,...,"When Eleonora is downloaded to the altar, her ...",Bachelorette fare sequel (2021).,0,0,0,0,0,default Value,NaN,NaN
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,...,A team building conference organized for a gro...,NaN,0,0,0,0,0,default Value,NaN,NaN
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,...,Once Ok-Ju worked as a bodyguard and was one o...,NaN,0,0,0,0,0,default Value,NaN,NaN
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,...,A great passionate of crime stories is trapped...,NaN,0,0,0,0,0,default Value,NaN,NaN

In [ ]:
# Apply Function, map for series
df['length_catagory'] = df['duration'].apply(lambda x: 'Long' if x > 120 else 'Short')
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,...,notes,humor,rhythm,effort,tension,erotism,reviewer,classic,must_watch,length_catagory
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,2007,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,...,"These are many small independent stories, whic...",3,3,0,0,0,default Value,NaN,NaN,Short
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,...,"Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0,default Value,True,True,Short
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,...,"""Ecological"" story with a happy ending, not wi...",1,2,1,0,0,default Value,True,True,Short
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,...,A cast of will be famous for Levinson's direct...,2,2,0,1,2,default Value,True,True,Short
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,...,Taken from the play by Armando Curcio that the...,3,1,1,0,0,default Value,True,True,Short
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,...,Freely taken from a true story.,0,0,0,0,0,default Value,NaN,NaN,Short
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,...,Bachelorette fare sequel (2021).,0,0,0,0,0,default Value,NaN,NaN,Short
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,...,NaN,0,0,0,0,0,default Value,NaN,NaN,Short
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,...,NaN,0,0,0,0,0,default Value,NaN,NaN,Short
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,...,NaN,0,0,0,0,0,default Value,NaN,NaN,Short

In [118]:
# Create a Data Frame with multiple series
data = {'A':[1,2,3],
        'B':[4,5,6],
        'C':[7,8,9]}
num_data = pd.DataFrame(data)
num_data

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [119]:
def sum_series(x,y):
    return x + y
result =num_data.apply(lambda row: sum_series(row['A'],row['B']),axis=1)
result

0    5
1    7
2    9
dtype: int64

In [121]:
df['country'].replace('USA','United States')
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,...,notes,humor,rhythm,effort,tension,erotism,reviewer,classic,must_watch,length_catagory
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,2007,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,...,"These are many small independent stories, whic...",3,3,0,0,0,default Value,NaN,NaN,Short
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,...,"Luigi Perelli, the director of the ""Piovra"", o...",0,2,0,2,0,default Value,True,True,Short
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,...,"""Ecological"" story with a happy ending, not wi...",1,2,1,0,0,default Value,True,True,Short
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,...,A cast of will be famous for Levinson's direct...,2,2,0,1,2,default Value,True,True,Short
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,...,Taken from the play by Armando Curcio that the...,3,1,1,0,0,default Value,True,True,Short
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,...,Freely taken from a true story.,0,0,0,0,0,default Value,NaN,NaN,Short
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,...,Bachelorette fare sequel (2021).,0,0,0,0,0,default Value,NaN,NaN,Short
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,...,NaN,0,0,0,0,0,default Value,NaN,NaN,Short
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,...,NaN,0,0,0,0,0,default Value,NaN,NaN,Short
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,...,NaN,0,0,0,0,0,default Value,NaN,NaN,Short

In [122]:
# Add new Column
df['title_year'] = df['title'] + " (" + df['year'].astype(str) + "}"
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,...,humor,rhythm,effort,tension,erotism,reviewer,classic,must_watch,length_catagory,title_year
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,2007,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,...,3,3,0,0,0,default Value,NaN,NaN,Short,Bugs Bunny's Third Movie: 1001 Rabbit Tales (2...
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,...,0,2,0,2,0,default Value,True,True,Short,18 anni tra una settimana (1991}
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,...,1,2,1,0,0,default Value,True,True,Short,Ride a Wild Pony (1976}
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,...,2,2,0,1,2,default Value,True,True,Short,Diner (1982}
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,...,3,1,1,0,0,default Value,True,True,Short,A che servono questi quattrini? (1942}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,...,0,0,0,0,0,default Value,NaN,NaN,Short,Gold Digger Killer (2021}
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,...,0,0,0,0,0,default Value,NaN,NaN,Short,Addio al nubilato 2 (2023}
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,...,0,0,0,0,0,default Value,NaN,NaN,Short,Konferensen (2023}
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,...,0,0,0,0,0,default Value,NaN,NaN,Short,Ballelina (2023}
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,...,0,0,0,0,0,default Value,NaN,NaN,Short,Invitación a un Asesinato (2023}

In [123]:
# Adding New columns using assign
df = df.assign(
    is_older = lambda x:x['year'] < 2000,
    duration_hours = lambda x:x['duration'] / 60
)
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,...,effort,tension,erotism,reviewer,classic,must_watch,length_catagory,title_year,is_older,duration_hours
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,2007,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,...,0,0,0,default Value,NaN,NaN,Short,Bugs Bunny's Third Movie: 1001 Rabbit Tales (2...,False,1.266667
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,...,0,2,0,default Value,True,True,Short,18 anni tra una settimana (1991},True,1.633333
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,...,1,0,0,default Value,True,True,Short,Ride a Wild Pony (1976},True,1.516667
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,...,0,1,2,default Value,True,True,Short,Diner (1982},True,1.583333
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,...,1,0,0,default Value,True,True,Short,A che servono questi quattrini? (1942},True,1.416667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,...,0,0,0,default Value,NaN,NaN,Short,Gold Digger Killer (2021},False,1.450000
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,...,0,0,0,default Value,NaN,NaN,Short,Addio al nubilato 2 (2023},False,1.500000
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,...,0,0,0,default Value,NaN,NaN,Short,Konferensen (2023},False,1.666667
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,...,0,0,0,default Value,NaN,NaN,Short,Ballelina (2023},False,1.533333
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,...,0,0,0,default Value,NaN,NaN,Short,Invitación a un Asesinato (2023},False,1.533333

In [124]:
# adding Name to index
df.index.names = ['movie_id']
df

,filmtv_id,title,year,genre,duration,country,directors,actors,avg_vote,critics_vote,...,effort,tension,erotism,reviewer,classic,must_watch,length_catagory,title_year,is_older,duration_hours
movie_id,,,,,,,,,,,,,,,,,,,,,
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,2007,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,...,0,0,0,default Value,NaN,NaN,Short,Bugs Bunny's Third Movie: 1001 Rabbit Tales (2...,False,1.266667
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,...,0,2,0,default Value,True,True,Short,18 anni tra una settimana (1991},True,1.633333
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,...,1,0,0,default Value,True,True,Short,Ride a Wild Pony (1976},True,1.516667
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,...,0,1,2,default Value,True,True,Short,Diner (1982},True,1.583333
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,...,1,0,0,default Value,True,True,Short,A che servono questi quattrini? (1942},True,1.416667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,...,0,0,0,default Value,NaN,NaN,Short,Gold Digger Killer (2021},False,1.450000
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,...,0,0,0,default Value,NaN,NaN,Short,Addio al nubilato 2 (2023},False,1.500000
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,...,0,0,0,default Value,NaN,NaN,Short,Konferensen (2023},False,1.666667
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,...,0,0,0,default Value,NaN,NaN,Short,Ballelina (2023},False,1.533333
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,...,0,0,0,default Value,NaN,NaN,Short,Invitación a un Asesinato (2023},False,1.533333

In [125]:
df.rename(columns={'year':'release_year','title':'movie_title'}, inplace=True)
df

,filmtv_id,movie_title,release_year,genre,duration,country,directors,actors,avg_vote,critics_vote,...,effort,tension,erotism,reviewer,classic,must_watch,length_catagory,title_year,is_older,duration_hours
movie_id,,,,,,,,,,,,,,,,,,,,,
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,2007,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,...,0,0,0,default Value,NaN,NaN,Short,Bugs Bunny's Third Movie: 1001 Rabbit Tales (2...,False,1.266667
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,...,0,2,0,default Value,True,True,Short,18 anni tra una settimana (1991},True,1.633333
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,...,1,0,0,default Value,True,True,Short,Ride a Wild Pony (1976},True,1.516667
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,...,0,1,2,default Value,True,True,Short,Diner (1982},True,1.583333
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,...,1,0,0,default Value,True,True,Short,A che servono questi quattrini? (1942},True,1.416667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,...,0,0,0,default Value,NaN,NaN,Short,Gold Digger Killer (2021},False,1.450000
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,...,0,0,0,default Value,NaN,NaN,Short,Addio al nubilato 2 (2023},False,1.500000
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,...,0,0,0,default Value,NaN,NaN,Short,Konferensen (2023},False,1.666667
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,...,0,0,0,default Value,NaN,NaN,Short,Ballelina (2023},False,1.533333
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,...,0,0,0,default Value,NaN,NaN,Short,Invitación a un Asesinato (2023},False,1.533333

In [126]:
# set maximum rows and columns to display
pd.set_option('display.max_rows',7)
pd.set_option('display.max_columns',5)
df

,filmtv_id,movie_title,...,is_older,duration_hours
movie_id,,,,,
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,...,False,1.266667
1,3,18 anni tra una settimana,...,True,1.633333
2,17,Ride a Wild Pony,...,True,1.516667
...,...,...,...,...,...
41396,232915,Konferensen,...,False,1.666667
41397,232919,Ballelina,...,False,1.533333
41398,232920,Invitación a un Asesinato,...,False,1.533333

In [127]:
# reset
pd.reset_option('display')
df

,filmtv_id,movie_title,release_year,genre,duration,country,directors,actors,avg_vote,critics_vote,...,effort,tension,erotism,reviewer,classic,must_watch,length_catagory,title_year,is_older,duration_hours
movie_id,,,,,,,,,,,,,,,,,,,,,
0,2,Bugs Bunny's Third Movie: 1001 Rabbit Tales,2007,Animation,76,United States,"David Detiege, Art Davis, Bill Perez",NaN,7.7,8.00,...,0,0,0,default Value,NaN,NaN,Short,Bugs Bunny's Third Movie: 1001 Rabbit Tales (2...,False,1.266667
1,3,18 anni tra una settimana,1991,Drama,98,Italy,Luigi Perelli,"Kim Rossi Stuart, Simona Cavallari, Ennio Fant...",6.5,6.00,...,0,2,0,default Value,True,True,Short,18 anni tra una settimana (1991},True,1.633333
2,17,Ride a Wild Pony,1976,Romantic,91,United States,Don Chaffey,"Michael Craig, John Meillon, Eva Griffith, Gra...",5.7,6.00,...,1,0,0,default Value,True,True,Short,Ride a Wild Pony (1976},True,1.516667
3,18,Diner,1982,Comedy,95,United States,Barry Levinson,"Mickey Rourke, Steve Guttenberg, Ellen Barkin,...",7.0,8.00,...,0,1,2,default Value,True,True,Short,Diner (1982},True,1.583333
4,20,A che servono questi quattrini?,1942,Comedy,85,Italy,Esodo Pratelli,"Eduardo De Filippo, Peppino De Filippo, Clelia...",5.9,5.33,...,1,0,0,default Value,True,True,Short,A che servono questi quattrini? (1942},True,1.416667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41394,232817,Gold Digger Killer,2021,Thriller,87,"Canada, United States",Robin Hays,"Julie Benz, Roan Curtis, Georgia Bradner, Eli ...",4.0,NaN,...,0,0,0,default Value,NaN,NaN,Short,Gold Digger Killer (2021},False,1.450000
41395,232893,Addio al nubilato 2,2023,Comedy,90,Italy,Francesco Apolloni,"Laura Chiatti, Chiara Francini, Antonia Liskov...",2.7,NaN,...,0,0,0,default Value,NaN,NaN,Short,Addio al nubilato 2 (2023},False,1.500000
41396,232915,Konferensen,2023,Horror,100,Sweden,Patrik Eklund,"Katia Winter, Eva Melander, Lola Zackow, Adam ...",6.0,NaN,...,0,0,0,default Value,NaN,NaN,Short,Konferensen (2023},False,1.666667
41397,232919,Ballelina,2023,Thriller,92,South Korea,Chung-Hyun Lee,"Jeon Jong-seo, Park Yu-rim, Ji-hun Kim",5.8,NaN,...,0,0,0,default Value,NaN,NaN,Short,Ballelina (2023},False,1.533333
41398,232920,Invitación a un Asesinato,2023,Thriller,92,Mexico,J.M Cravioto,"Maribel Verdú, Stephanie Cayo, Manolo Cardona,...",6.0,NaN,...,0,0,0,default Value,NaN,NaN,Short,Invitación a un Asesinato (2023},False,1.533333

In [128]:
# Grouping
genre_groups = df.groupby('genre')
genre_groups

In [130]:
for genre, group_data in genre_groups:
    print(f"Genre: {genre}")
    print(group_data)
    print()

Genre: Action
          filmtv_id           movie_title  release_year   genre  duration  \
movie_id
15               38          Mr. Majestyk          1974  Action       105
16               45          Warning Sign          1985  Action        99
109             193           Airport '77          1977  Action       110
342             530   Wings of the Apache          1990  Action        86
369             574  Geheimcode Wildgänse          1985  Action        93
...             ...                   ...           ...     ...       ...
41308        225561    Tin joek yau ching          1990  Action        87
41314        226116          Blood & Gold          2023  Action       100
41337        228408          Kung Fu Girl          2021  Action        98
41343        229097               Hit Man          2023  Action       113
41378        231061            Sentinelle          2023  Action        99

                country                         directors  \
movie_id
15        United States                 Richard Fleischer
16        United States                       Hal Barwood
109       United States                     Jerry Jameson
342       United States                       David Green
369               Italy                Antonio Margheriti
...                 ...                               ...
41308         Hong Kong                        Benny Chan
41314           Germany                   Peter Thorwarth
41337     United States           Devon Downs, Kenny Gage
41343     United States                 Richard Linklater
41378            France  Hugo Benamozig, David Caviglioli

                                                     actors  avg_vote  \
movie_id
15        Charles Bronson, Linda Cristal, Al Lettieri, L...       6.2
16        Sam Waterston, Kathleen Quinlan, Yaphet Kotto,...       4.8
109       Jack Lemmon, James Stewart, Lee Grant, Brenda ...       4.7
342       Nicolas Cage, Sean Young, Tommy Lee Jones, Dal...       4.6
369       Lewis Collins, Lee Van Cleef, Ernest Borgnine,...       4.9
...                                                     ...       ...
41308     Andy Lau, Chien-lien Wu, Man-Tat Ng, Kwong-Leu...       7.5
41314     Jördis Triebel, Alexander Scheer, Robert Maase...       6.1
41337     Danny Kwok-Kwan Chan, Yixi Tao, Shuting Li, Xi...       4.5
41343     Adria Arjona, Glen Powell, Retta, Austin Ameli...       7.1
41378     Jonathan Cohen, Emmanuelle Bercot, Raphaël Que...       4.0

          critics_vote  ...  effort  tension erotism       reviewer  classic  \
movie_id                ...
15                5.71  ...       3        3       0  default Value     True
16                4.00  ...       1        1       0  default Value     True
109               3.33  ...       0        1       0  default Value     True
342               4.00  ...       0        1       1  default Value     True
369               3.50  ...       0        2       0  default Value     True
...                ...  ...     ...      ...     ...            ...      ...
41308             7.00  ...       0        0       0  default Value     True
41314             5.67  ...       0        0       0  default Value      NaN
41337              NaN  ...       0        0       0  default Value      NaN
41343             7.00  ...       0        0       0  default Value      NaN
41378              NaN  ...       0        0       0  default Value      NaN

          must_watch  length_catagory                   title_year  is_older  \
movie_id
15              True            Short          Mr. Majestyk (1974}      True
16              True            Short          Warning Sign (1985}      True
109             True            Short           Airport '77 (1977}      True
342             True            Short   Wings of the Apache (1990}      True
369             True            Short  Geheimcode Wildgänse (1985}      True
...              ...              ...                          ...       ...
41308           True            Short    Tin joek yau ching (1990}      True
41314            NaN            Short          Blood & Gold (2023}     False
41337            NaN            Short          Kung Fu Girl (2021}     False
41343            NaN            Short               Hit Man (2023}     False
41378            NaN            Short            Sentinelle (2023}     False

         duration_hours
movie_id
15             1.750000
16             1.650000
109            1.833333
342            1.433333
369            1.550000
...                 ...
41308          1.450000
41314          1.666667
41337          1.633333
41343          1.883333
41378          1.650000

[2155 rows x 26 columns]

Genre: Adventure
          filmtv_id                       movie_title  release_year  \
movie_id
10               30         A Ghentar si muore facile          1968
20               53                A qualsiasi prezzo          1968
33               74                          The Deep          1977
82              145                    Africa Express          1975
83              146               Africa sotto i mari          1952
...             ...                               ...           ...
41222        222074                   We Have a Ghost          2023
41230        222398          Tremors: Shrieker Island          2020
41274        224588             Knights of the Zodiac          2023
41293        225497  Coast Guard Malaysia: Ops Helang          2023
41330        227960                     Hidden Strike          2023

              genre  duration                        country  \
movie_id
10        Adventure       101                          Italy
20        Adventure        94                          Italy
33        Adventure       130                  United States
82        Adventure        95                          Italy
83        Adventure        95                          Italy
...             ...       ...                            ...
41222     Adventure       126                  United States
41230     Adventure       103                  United States
41274     Adventure       112  Japan, Hungary, United States
41293     Adventure        90                       Malaysia
41330     Adventure       102           China, United States

                   directors  \
movie_id
10            Leon Klimovsky
20           Emilio Miraglia
33               Peter Yates
82              Michele Lupo
83         Giovanni Roccardi
...                      ...
41222     Christopher Landon
41230       Don Michael Paul
41274        Tomasz Baginski
41293             Pitt Hanif
41330            Scott Waugh

                                                     actors  avg_vote  \
movie_id
10        George Hilton, Ennio Girolami, Marta Padovan, ...       4.8
20        Walter Pidgeon, Ira Fürstenberg, Klaus Kinski,...       3.8
33        Nick Nolte, Jacqueline Bisset, Robert Shaw, El...       5.3
82        Giuliano Gemma, Ursula Andress, Jack Palance, ...       5.1
83        Sophia Loren, Stephen Barclay, Umberto Melnati...       4.1
...                                                     ...       ...
41222     Jennifer Coolidge, David Harbour, Anthony Mack...       6.2
41230     Michael Gross, Jon Heder, Richard Brake, Carol...       5.6
41274     Famke Janssen, Sean Bean, Madison Iseman, Mark...       3.4
41293     Saharul Ridzwan, Julia Farhana Marin, Sabri Yu...       3.5
41330     Jackie Chan, John Cena, Pilou Asbæk, Rachael H...       6.0

          critics_vote  ...  effort  tension erotism       reviewer  classic  \
movie_id                ...
10                4.50  ...       0        1       0  default Value     True
20                4.00  ...       0        1       1  default Value     True
33                4.88  ...       1        2       1  default Value     True
82                5.50  ...       0        1       1  default Value     True
83                4.00  ...       0        1       2  default Value     True
...                ...  ...     ...      ...     ...            ...      ...
41222             6.00  ...       0        0       0  default Value      NaN
41230             5.00  ...       0        0       0  default Value      NaN
41274             3.00  ...       0        0       0  default Value      NaN
41293             3.00  ...       0        0       0  default Value      NaN
41330              NaN  ...       0        0       0  default Value      NaN

          must_watch  length_catagory  \
movie_id
10              True            Short
20              True            Short
33              True             Long
82              True            Short
83              True            Short
...              ...              ...
41222            NaN             Long
41230            NaN            Short
41274            NaN            Short
41293            NaN            Short
41330            NaN            Short

                                       title_year  is_older duration_hours
movie_id
10               A Ghentar si muore facile (1968}      True       1.683333
20                      A qualsiasi prezzo (1968}      True       1.566667
33                                The Deep (1977}      True       2.166667
82                          Africa Express (1975}      True       1.583333
83                     Africa sotto i mari (1952}      True       1.583333
...                                           ...       ...            ...
41222                      We Have a Ghost (2023}     False       2.100000
41230             Tremors: Shrieker Island (2020}     False       1.716667
41274                Knights of the Zodiac (2023}     False       1.866667
41293     Coast Guard Malaysia: Ops Helang (2023}     False       1.500000
41330                        Hidden Strike (2023}     False       1.700000

[1524 rows x 26 columns]

Genre: Animation
          filmtv_id                                  movie_title  \
movie_id
0                 2  Bugs Bunny's Third Movie: 1001 Rabbit Tales
159             260                         The Land Before Time
167             271                           Allegro non troppo
435             679                 Asterix et le coup de menhir
715            1093                           The Secret Of Nimh
...             ...                                          ...
41256        223768  Teenage Mutant Ninja Turtles: Mutant Mayhem
41257        223769                          The First Slam Dunk
41266        224224                 Ruby Gillman, Teenage Kraken
41348        229395                  Lonely Castle in the Mirror
41363        229825                                      Invelle

          release_year      genre  duration        country  \
movie_id
0                 2007  Animation        76  United States
159               1988  Animation        79  United States
167               1977  Animation        85          Italy
435               1989  Animation        81         France
715               1982  Animation        82  United States
...                ...        ...       ...            ...
41256             2023  Animation        99  United States
41257             2022  Animation       124          Japan
41266             2023  Animation        91  United States
41348             2022  Animation       116          Japan
41363             2023  Animation        96          Italy

                                     directors  \
movie_id
0         David Detiege, Art Davis, Bill Perez
159                                  Don Bluth
167                             Bruno Bozzetto
435                           Philippe Grimond
715                                  Don Bluth
...                                        ...
41256                  Jeff Rowe, Kyler Spears
41257           Takehiko Inoue, Yasuyuki Ebara
41266                             Kirk DeMicco
41348          Keiichi Hara, Takakazu Nagatomo
41363                             Simone Massi

                                                     actors  avg_vote  \
movie_id
0                                                       NaN       7.7
159                                                     NaN       7.4
167       Maurizio Nichetti, Maurizio Micheli, Maria Lui...       7.6
435                                                     NaN       6.8
715                                                     NaN       8.2
...                                                     ...       ...
41256                                                   NaN       6.4
41257                                                   NaN       8.0
41266                                                   NaN       6.0
41348                                                   NaN       6.7
41363                                                   NaN       9.0

          critics_vote  ...  effort  tension erotism       reviewer  classic  \
movie_id                ...
0                 8.00  ...       0        0       0  default Value      NaN
159               7.50  ...       0        1       0  default Value     True
167               7.71  ...       2        0       0  default Value     True
435               6.67  ...       0        0       0  default Value     True
715               8.50  ...       0        2       0  default Value     True
...                ...  ...     ...      ...     ...            ...      ...
41256             6.50  ...       0        0       0  default Value      NaN
41257              NaN  ...       0        0       0  default Value      NaN
41266             7.00  ...       0        0       0  default Value      NaN
41348             6.50  ...       1        1       1  default Value      NaN
41363             8.50  ...       0        0       0  default Value      NaN

          must_watch  length_catagory  \
movie_id
0                NaN            Short
159             True            Short
167             True            Short
435             True            Short
715             True            Short
...              ...              ...
41256            NaN            Short
41257            NaN             Long
41266            NaN            Short
41348            NaN            Short
41363            NaN            Short

                                                 title_year  is_older  \
movie_id
0         Bugs Bunny's Third Movie: 1001 Rabbit Tales (2...     False
159                             The Land Before Time (1988}      True
167                               Allegro non troppo (1977}      True
435                     Asterix et le coup de menhir (1989}      True
715                               The Secret Of Nimh (1982}      True
...                                                     ...       ...
41256     Teenage Mutant Ninja Turtles: Mutant Mayhem (2...     False
41257                            The First Slam Dunk (2022}     False
41266                   Ruby Gillman, Teenage Kraken (2023}     False
41348                    Lonely Castle in the Mirror (2022}     False
41363                                        Invelle (2023}     False

         duration_hours
movie_id
0              1.266667
159            1.316667
167            1.416667
435            1.350000
715            1.366667
...                 ...
41256          1.650000
41257          2.066667
41266          1.516667
41348          1.933333
41363          1.600000

[1076 rows x 26 columns]

Genre: Biblical
          filmtv_id                         movie_title  release_year  \
movie_id
615             942                             Ben Hur          1959
1419           2119                The Ten Commandments          1956
1697           2531                     Erode il Grande          1958
2114           3151                 Giuditta e Oloferne          1958
2124           3167       Giuseppe venduto dai fratelli          1961
2863           4274                           Il Messia          1975
3563           5347        The Greatest Story Ever Told          1965
3896           5854                   The King of Kings          1961
4453           6677                 La spada e la croce          1959
4549           6836                   The Story of Ruth          1960
4919           7372                            The Robe          1953
5940           9031                   Solomon and Sheba          1959
6826          10368                       David e Golia          1959
8392          12762  Genesi - La Creazione e il Diluvio          1994
8434          12825                       Ester e il re          1960
10942         16849                              Esther          1985
11573         17935                        Il quarto re          1997
12595         19554                     Maria Maddalena          2000
13469         21090                               Giuda          2000
13493         21135                             Tommaso          2001
13955         21910                Giuseppe di Nazareth          1999
15262         24080          San Giovanni. L'Apocalisse          2002
16603         26238                          Noah's Ark          1999
16660         26341           The Passion of the Christ          2004
20557         35707                    Gesù di Nazareth          1977
24155         42350                    Viaggiu dulurusu          1992
24204         42430                   The King of Kings          1927
27294         51072                              Salome          1922
27423         51481                    Maria di Nazaret          2012
28105         54251                             Ben Hur          2010
28470         56046                            Jeremiah          1998
28996         58832                          San Pietro          2005
29311         60587                             Solomon          1997
29414         61169                   Paul the Apostole          2000
30100         65370                          Son of God          2014
31873         76154                  Samson and Delilah          1996
31902         76434                               David          1997
35781        150491                              Samson          2018

             genre  duration  \
movie_id
615       Biblical       212
1419      Biblical       220
1697      Biblical        95
2114      Biblical        94
2124      Biblical       102
2863      Biblical       140
3563      Biblical       200
3896      Biblical       168
4453      Biblical       106
4549      Biblical       132
4919      Biblical       135
5940      Biblical       120
6826      Biblical       113
8392      Biblical       101
8434      Biblical       109
10942     Biblical        90
11573     Biblical        90
12595     Biblical        93
13469     Biblical        90
13493     Biblical        90
13955     Biblical        96
15262     Biblical       130
16603     Biblical       130
16660     Biblical       126
20557     Biblical       371
24155     Biblical        41
24204     Biblical       112
27294     Biblical        72
27423     Biblical       200
28105     Biblical       180
28470     Biblical        90
28996     Biblical       200
29311     Biblical       180
29414     Biblical       170
30100     Biblical       138
31873     Biblical       172
31902     Biblical       190
35781     Biblical       116

                                                    country  \
movie_id
615                                           United States
1419                                          United States
1697                                                  Italy
2114                                                  Italy
2124                                      Italy, Yugoslavia
2863                                          Italy, France
3563                                          United States
3896                                          United States
4453                                                  Italy
4549                                          United States

In [131]:
# Average Duration
avg_duration_by_genre = df.groupby('genre')['duration'].mean()
avg_duration_by_genre

genre
Action             101.682599
Adventure          102.870079
Animation           88.925651
Biblical           137.210526
Biography          120.602920
Comedy              97.881409
Crime               98.939914
Documentary         92.641638
Drama              105.271266
Erotico             90.893617
Fantasy            105.612326
Gangster           117.803571
Grotesque           99.851852
History            127.159420
Horror              92.603867
Musical            106.240654
Mythology           97.969697
Mélo               107.836538
Noir                98.428571
Romantic            94.778571
Sci-Fi             102.097238
Short Movie        210.500000
Sperimental         97.716049
Sport               95.428571
Spy                105.333333
Stand-up Comedy     73.000000
Super-hero         121.855422
Thriller            97.957849
War                111.306173
Western             95.800175
Name: duration, dtype: float64

In [134]:
# Group By multiple columns
stats_by_genre = df.groupby('genre')['avg_vote'].agg([np.mean,np.std,np.min,np.max])
stats_by_genre

C:\Users\Sudhe\AppData\Local\Temp\ipykernel_30656\225588405.py:2: FutureWarning: The provided callable <function mean at 0x0000017BFABD7F60> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  stats_by_genre = df.groupby('genre')['avg_vote'].agg([np.mean,np.std,np.min,np.max])
C:\Users\Sudhe\AppData\Local\Temp\ipykernel_30656\225588405.py:2: FutureWarning: The provided callable <function std at 0x0000017BFABDC0E0> is currently using SeriesGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  stats_by_genre = df.groupby('genre')['avg_vote'].agg([np.mean,np.std,np.min,np.max])
C:\Users\Sudhe\AppData\Local\Temp\ipykernel_30656\225588405.py:2: FutureWarning: The provided callable <function min at 0x0000017BFABD76A0> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  stats_by_genre = df.groupby('genre')['avg_vote'].agg([np.mean,np.std,np.min,np.max])
C:\Users\Sudhe\AppData\Local\Temp\ipykernel_30656\225588405.py:2: FutureWarning: The provided callable <function max at 0x0000017BFABD7560> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  stats_by_genre = df.groupby('genre')['avg_vote'].agg([np.mean,np.std,np.min,np.max])

                     mean       std  min   max
genre
Action           5.123898  1.399433  1.0   9.0
Adventure        5.545866  1.324040  1.4   9.3
Animation        6.118030  1.281681  1.6   9.3
Biblical         5.184211  1.273753  2.9   8.2
Biography        5.949051  1.208300  1.0  10.0
Comedy           5.482645  1.355306  1.0  10.0
Crime            6.142918  1.167942  2.7   8.8
Documentary      6.564749  1.180058  1.0  10.0
Drama            6.292677  1.302034  1.0  10.0
Erotico          4.052766  1.323337  1.0   7.9
Fantasy          5.486282  1.322481  1.3   9.4
Gangster         6.614286  1.383333  2.5   9.0
Grotesque        6.458848  1.250535  2.3   9.1
History          5.887681  1.245398  2.7   8.8
Horror           5.225874  1.301247  1.3   9.1
Musical          6.016121  1.474926  1.8   9.0
Mythology        4.631818  1.298183  2.2   8.0
Mélo             6.715385  1.256731  3.6   8.6
Noir             6.985294  1.104915  3.4   9.5
Romantic         4.883367  1.532141  1.0   8.8
Sci-Fi           5.484309  1.365001  1.4   9.2
Short Movie      6.800000  0.843801  5.3   7.7
Sperimental      6.547531  1.170454  2.0   9.0
Sport            5.228571  1.879463  3.0   7.5
Spy              5.769167  1.399898  2.0   8.8
Stand-up Comedy  7.325000  0.793200  6.8   8.5
Super-hero       5.833735  1.032671  2.3   7.5
Thriller         5.530586  1.264825  1.0   9.3
War              6.293086  1.301066  1.7   9.3
Western          5.744590  1.306447  1.5   8.9

In [137]:
# Complex Aggeregation
complex_aggregation = df.groupby('genre').agg({
    'duration' : np.mean,
    'avg_vote' : [np.min,np.max],
    'public_vote' : 'sum'
})
complex_aggregation

C:\Users\Sudhe\AppData\Local\Temp\ipykernel_30656\3815286703.py:2: FutureWarning: The provided callable <function mean at 0x0000017BFABD7F60> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  complex_aggregation = df.groupby('genre').agg({
C:\Users\Sudhe\AppData\Local\Temp\ipykernel_30656\3815286703.py:2: FutureWarning: The provided callable <function min at 0x0000017BFABD76A0> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  complex_aggregation = df.groupby('genre').agg({
C:\Users\Sudhe\AppData\Local\Temp\ipykernel_30656\3815286703.py:2: FutureWarning: The provided callable <function max at 0x0000017BFABD7560> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  complex_aggregation = df.groupby('genre').agg({

                   duration avg_vote       public_vote
                       mean      min   max         sum
genre
Action           101.682599      1.0   9.0     11369.0
Adventure        102.870079      1.4   9.3      8747.0
Animation         88.925651      1.6   9.3      6639.0
Biblical         137.210526      2.9   8.2       202.0
Biography        120.602920      1.0  10.0      4136.0
Comedy            97.881409      1.0  10.0     51634.0
Crime             98.939914      2.7   8.8      2953.0
Documentary       92.641638      1.0  10.0     13371.0
Drama            105.271266      1.0  10.0     76234.0
Erotico           90.893617      1.0   7.9       981.0
Fantasy          105.612326      1.3   9.4      2830.0
Gangster         117.803571      2.5   9.0       378.0
Grotesque         99.851852      2.3   9.1      1578.0
History          127.159420      2.7   8.8       823.0
Horror            92.603867      1.3   9.1     12917.0
Musical          106.240654      1.8   9.0      2647.0
Mythology         97.969697      2.2   8.0       338.0
Mélo             107.836538      3.6   8.6       705.0
Noir              98.428571      3.4   9.5      1640.0
Romantic          94.778571      1.0   8.8      4906.0
Sci-Fi           102.097238      1.4   9.2      5064.0
Short Movie      210.500000      5.3   7.7        41.0
Sperimental       97.716049      2.0   9.0      1018.0
Sport             95.428571      3.0   7.5        37.0
Spy              105.333333      2.0   8.8      1406.0
Stand-up Comedy   73.000000      6.8   8.5        32.0
Super-hero       121.855422      2.3   7.5       488.0
Thriller          97.957849      1.0   9.3     21048.0
War              111.306173      1.7   9.3      2596.0
Western           95.800175      1.5   8.9      6739.0

In [9]:
# overall Stats
overall_stats = df[['duration','avg_vote']].describe
overall_stats

<bound method NDFrame.describe of        duration  avg_vote
0            76       7.7
1            98       6.5
2            91       5.7
3            95       7.0
4            85       5.9
...         ...       ...
41394        87       4.0
41395        90       2.7
41396       100       6.0
41397        92       5.8
41398        92       6.0

[41399 rows x 2 columns]>

In [12]:
# Create a DataFrame .count - not Null Values
data = {'A' : [1,2,None],'B':[4,None,6],'C' :[None,5,9]}
data_df = pd.DataFrame(data)
counts = data_df.count()
counts

A    2
B    2
C    2
dtype: int64

In [13]:
# Values Count
df['title'].value_counts

<bound method IndexOpsMixin.value_counts of 0        Bugs Bunny's Third Movie: 1001 Rabbit Tales
1                          18 anni tra una settimana
2                                   Ride a Wild Pony
3                                              Diner
4                    A che servono questi quattrini?
                            ...
41394                             Gold Digger Killer
41395                            Addio al nubilato 2
41396                                    Konferensen
41397                                      Ballelina
41398                      Invitación a un Asesinato
Name: title, Length: 41399, dtype: object>