In [11]:
from io import StringIO, BytesIO
import numpy as np
import pandas as pd

In [9]:
data = ('col1,col2,col3\n1,2,3\n4,5,6\n7,8,9')
type(data)
print(data)

col1,col2,col3
1,2,3
4,5,6
7,8,9

In [12]:
pd.read_csv(StringIO(data))

   col1  col2  col3
0     1     2     3
1     4     5     6
2     7     8     9

In [16]:
# Get Specific Column
pd.read_csv(StringIO(data), usecols=['col2', 'col3'])

   col2  col3
0     2     3
1     5     6
2     8     9

In [17]:
# Get specific rows
pd.read_csv(StringIO(data), skiprows=1, nrows=2)

   1  2  3
0  4  5  6
1  7  8  9

In [18]:
data = 'Name,Age,City\nAlice,30,New York\nBob,25,Los Angeles\nCharlie,35,Chicago'
print(data)

Name,Age,City
Alice,30,New York
Bob,25,Los Angeles
Charlie,35,Chicago

In [25]:
df = pd.read_csv(StringIO(data),dtype='object')
#print(df)
print(df['Age'])

0    30
1    25
2    35
Name: Age, dtype: object

In [30]:
df = pd.read_csv(StringIO(data),dtype={'Age': float})
print(df['Age'])
print(df.dtypes)

0    30.0
1    25.0
2    35.0
Name: Age, dtype: float64
Name     object
Age     float64
City     object
dtype: object

In [32]:
df = pd.read_csv(StringIO(data))
print(df)

      Name  Age         City
0    Alice   30     New York
1      Bob   25  Los Angeles
2  Charlie   35      Chicago

In [39]:
data = 'index,Name,Age,city\na,Alice,30,New York\nb,Bob,25,Los Angeles\nc,Charlie,35,Chicago\nd,David,40,Houston\ne,Eve,28,Phoenix'
print(data)
df = pd.read_csv(StringIO(data), index_col=0)
print(df)

index,Name,Age,city
a,Alice,30,New York
b,Bob,25,Los Angeles
c,Charlie,35,Chicago
d,David,40,Houston
e,Eve,28,Phoenix
          Name  Age         city
index
a        Alice   30     New York
b          Bob   25  Los Angeles
c      Charlie   35      Chicago
d        David   40      Houston
e          Eve   28      Phoenix